### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by paultibbetts** [ptibbetts/allusion#1]
- [x] Add README.md #2
- [x] Change CONTRIBUTING.md from Sage details to my own #3
- [x] Add support for displaying an "article"
- [x] Add support for displaying a "note"
- [x] Add support for displaying a "link"
- [x] Add h-card

**Comment by paultibbetts** [comment]
https://github.com/ptibbetts/allusion/releases/tag/v1.0.0
